In [8]:
import numpy as np
import pandas as pd
import re

In [13]:
with open("input.txt", "r") as f:
    lines = [x.strip() for x in f.readlines()]

df = pd.DataFrame({"line": lines})

df[["winning", "have"]] = df["line"].str.extract(".*: (.*) \\| (.*)")
df = df.drop("line", axis = 1)

df["overlap"] = df.apply(lambda row: list(set(row["winning"]).intersection(row["have"])), axis = 1)

df

,winning,have,overlap
0,77 45 9 81 96 5 91 3 66 76,7 56 66 49 96 58 54 34 37 5 14 85 45 91 9 2...,"[ , 4, 8, 5, 9, 1, 3, 7, 6]"
1,41 49 12 46 39 9 72 78 24 76,3 28 60 82 2 26 67 75 37 72 64 46 54 13 85 2...,"[ , 4, 2, 8, 9, 1, 3, 7, 6]"
2,26 93 49 51 21 50 33 69 73 28,64 18 76 80 65 89 78 38 37 75 14 91 44 72 94 5...,"[ , 4, 0, 2, 8, 5, 9, 1, 3, 7, 6]"
3,75 85 30 17 82 27 51 28 94 90,2 6 1 83 65 21 30 70 22 91 11 26 47 95 59 9...,"[ , 4, 0, 2, 8, 5, 9, 1, 3, 7]"
4,95 59 90 56 69 67 12 57 6 68,61 52 76 69 67 40 31 56 55 90 12 68 32 66 2 9...,"[ , 0, 2, 8, 5, 9, 1, 7, 6]"
...,...,...,...
187,84 96 45 41 89 7 4 78 15 67,50 81 20 90 83 39 37 23 95 69 10 25 35 36 66 7...,"[ , 4, 8, 5, 9, 1, 7, 6]"
188,17 79 92 4 56 68 1 91 33 82,5 84 58 42 73 9 86 59 48 44 52 55 43 30 93 5...,"[ , 4, 2, 8, 5, 9, 1, 3, 7, 6]"
189,87 29 43 80 97 27 41 95 23 25,21 84 53 11 41 50 62 15 18 26 90 77 55 37 16 9...,"[ , 4, 0, 2, 8, 5, 9, 1, 3, 7]"
190,8 40 10 80 85 87 41 23 15 37,58 27 21 41 62 1 71 43 18 26 38 4 3 2 29 9...,"[ , 4, 0, 2, 8, 5, 1, 3, 7]"
191,5 89 88 49 70 26 73 3 56 64,38 29 37 69 59 14 22 78 66 9 75 86 13 96 52 1...,"[ , 5, 4, 0, 2, 8, 9, 3, 7, 6]"